### ISSUE TITLE
Windows Forms - Template updates

### ISSUE THREAD

**Issue by doterik** [egvijayanand/dotnet6-project-templates#17]
Just found your templates, they look very promising.

What about the new [template updates for Windows Forms](https://devblogs.microsoft.com/dotnet/whats-new-in-windows-forms-in-net-6-0/?utm_source=vs_developer_news&utm_medium=referral#template-updates)?

File-scoped namespaces, a matter of taste I suppose, but other changes may be something to consider...

![image](https://user-images.githubusercontent.com/4037602/142446242-88970c72-69ad-41a8-a129-afcb569719f5.png)

**Comment by egvijayanand** [comment]
Hello @doterik,

The objective of these templates is to eliminate repetitive tasks and simplify things.

Was going through the same article you've mentioned for streamlining the application bootstrap.

Planning to induct them in the next update.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hello @doterik, 

Updated templates are now available to download from NuGet:

* Unified template - v1.0.5
* WinForms template - v1.0.9
* WPF template - v1.0.10

Happy coding. Stay connected with my [Developer Thoughts](https://egvijayanand.in/) blog for working with Blazor and .NET MAUI.

Regards,
Vijay Anand E G

**Comment by doterik** [comment]
@egvijayanand Great, I like your templates and your _Developer Thoughts_...

**Comment by egvijayanand** [comment]
@doterik, very pleased to hear that it serves the intended purpose.

Stay connected for more insights on the exciting new features.
